/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.bean.Produto;
import model.bean.ProdutoDAO;
import model.bean.Saldo;
import model.bean.SaldoDAO;

/**
 *
 * @author Aluno
 */
public class labelLista extends javax.swing.JFrame {

    /**
     * Creates new form labelLista
     */
    public labelLista() {
        initComponents();
       ProdutoDAO dao = new ProdutoDAO();
        for(Produto p: dao.read()){
            
            ComboBoxList.addItem(p);
        }
         DefaultTableModel modelo=(DefaultTableModel)TableList.getModel();
        modelo.setNumRows(0);
        
        
        SaldoDAO sdao = new SaldoDAO();
        for(Saldo s: sdao.read()){
            valor2=s.getEntrada();
            valor3=s.getSaida();
            saldo=(valor2-valor3);
            descri=s.getDescricaoProduto();
             modelo.addRow(new Object[]{descri,saldo});
        }
    }
    int valor1,valor2,valor3,saldo;
    String descri;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVoltarLP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableList = new javax.swing.JTable();
        ComboBoxList = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        buttonVoltarLP.setText("Voltar");
        buttonVoltarLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarLPActionPerformed(evt);
            }
        });

        TableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableList);

        ComboBoxList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxListItemStateChanged(evt);
            }
        });
        ComboBoxList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonVoltarLP)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ComboBoxList, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonVoltarLP)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarLPActionPerformed
        // TODO add your handling code here:
        new labelprincipal().setVisible(true);
            dispose();
    }//GEN-LAST:event_buttonVoltarLPActionPerformed

    private void ComboBoxListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxListItemStateChanged
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_ComboBoxListItemStateChanged

    private void ComboBoxListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxListActionPerformed
        // TODO add your handling code here:
         
         Produto produto = (Produto) ComboBoxList.getSelectedItem();
        valor1 = produto.getCodigoProduto();
        DefaultTableModel dm = (DefaultTableModel)TableList.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
       // System.out.println(valor1);
       DefaultTableModel modelo=(DefaultTableModel)TableList.getModel();
        modelo.setNumRows(0);
        SaldoDAO sdao = new SaldoDAO();
      List<Saldo> se = sdao.readExpec(valor1);
            valor2= se.get(0).getEntrada();
            valor3= se.get(0).getSaida();
            saldo=(valor2-valor3);
            descri=se.get(0).getDescricaoProduto();
             modelo.addRow(new Object[]{descri,saldo});
        
       
       
    }//GEN-LAST:event_ComboBoxListActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ComboBoxList.setSelectedItem(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(labelLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(labelLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(labelLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(labelLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new labelLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> ComboBoxList;
    private javax.swing.JTable TableList;
    private javax.swing.JButton buttonVoltarLP;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
