/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DateFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.Date;

/**
 *
 * @author Aluno
 */
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Historico;
import model.bean.HistoricoDAO;
import model.bean.Produto;
import model.bean.ProdutoDAO;
public class labelEntrada extends javax.swing.JFrame {

    /**
     * Creates new form labelEntrada
     */
    public labelEntrada() throws ParseException {
        initComponents();
        
        ProdutoDAO dao = new ProdutoDAO();
        
        for(Produto p: dao.read()){
            ComboBoxDE.addItem(p);
        }
       
    }
    int valor1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVoltarEP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxDE = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtQuantiE = new javax.swing.JTextField();
        txtDataE = new javax.swing.JTextField();
        ButtonEntrada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        buttonVoltarEP.setText("Voltar");
        buttonVoltarEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarEPActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entrada");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quantidade");

        txtQuantiE.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtDataE.setEditable(false);
        txtDataE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDataE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataEActionPerformed(evt);
            }
        });

        ButtonEntrada.setText("ENTRADA");
        ButtonEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(326, Short.MAX_VALUE)
                        .addComponent(buttonVoltarEP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxDE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtQuantiE)
                            .addComponent(txtDataE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(ButtonEntrada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantiE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDataE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(buttonVoltarEP)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarEPActionPerformed
        // TODO add your handling code here:
        new labelprincipal().setVisible(true);
            dispose();
    }//GEN-LAST:event_buttonVoltarEPActionPerformed

    private void txtDataEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataEActionPerformed
        // TODO add your handling code here:
     
        
    }//GEN-LAST:event_txtDataEActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         LocalDate it = LocalDate.now();
        
     DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
        String data = it.format(formato);
        
        txtDataE.setText(data);
    }//GEN-LAST:event_formWindowOpened

    private void ButtonEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEntradaActionPerformed
        // TODO add your handling code here:
        Produto produto = (Produto) ComboBoxDE.getSelectedItem();
        valor1 = produto.getCodigoProduto();
        
        Historico h = new Historico();
        HistoricoDAO dao = new HistoricoDAO();
        
        h.setCodigoProduto(valor1);
        h.setQuantidade(Integer.parseInt(txtQuantiE.getText()));
        h.setOperacao("Entrada");
        dao.create(h);
        
        JOptionPane.showMessageDialog(null,"Entrada realizada com sucesso!");
        txtQuantiE.setText("");
        ComboBoxDE.setSelectedItem(null);
    }//GEN-LAST:event_ButtonEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(labelEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(labelEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(labelEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(labelEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new labelEntrada().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(labelEntrada.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEntrada;
    private javax.swing.JComboBox<Object> ComboBoxDE;
    private javax.swing.JButton buttonVoltarEP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDataE;
    private javax.swing.JTextField txtQuantiE;
    // End of variables declaration//GEN-END:variables
}
