/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import model.bean.Historico;
import model.bean.HistoricoDAO;
import model.bean.Produto;
import model.bean.ProdutoDAO;
import model.bean.Saldo;
import model.bean.SaldoDAO;

/**
 *
 * @author Aluno
 */
public class labelSaida extends javax.swing.JFrame {

    /**
     * Creates new form labelSaida
     */
    public labelSaida() {
        initComponents();
        
       ProdutoDAO dao = new ProdutoDAO();
       
       for(Produto p: dao.read()){
           
           ComboBoxDS.addItem(p);
       }
        
    }
    int valor1, valor2;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVoltarSP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxDS = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtQuantiS = new javax.swing.JTextField();
        txtDataS = new javax.swing.JTextField();
        ButtonSaida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        buttonVoltarSP.setText("Voltar");
        buttonVoltarSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarSPActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Saída");

        ComboBoxDS.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quantidade");

        txtQuantiS.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtDataS.setEditable(false);
        txtDataS.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ButtonSaida.setText("Saída");
        ButtonSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(326, Short.MAX_VALUE)
                        .addComponent(buttonVoltarSP))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDataS)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(ComboBoxDS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQuantiS))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(ButtonSaida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ComboBoxDS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtQuantiS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDataS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonVoltarSP)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarSPActionPerformed
        // TODO add your handling code here:
        new labelprincipal().setVisible(true);
            dispose();
    }//GEN-LAST:event_buttonVoltarSPActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LocalDate it = LocalDate.now();
        
     DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
        String data = it.format(formato);
        
        txtDataS.setText(data);
    }//GEN-LAST:event_formWindowOpened

    private void ButtonSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaidaActionPerformed
        // TODO add your handling code here:
        Produto produto = (Produto) ComboBoxDS.getSelectedItem();
        valor1 = produto.getCodigoProduto();
       
        SaldoDAO sdao = new SaldoDAO(); 
        for(Saldo s: sdao.readS(valor1)){
            valor2=s.getSaida();
        }
        System.out.println(valor2);
        if(Integer.parseInt(txtQuantiS.getText())<valor2){
        Historico h = new Historico();
        HistoricoDAO dao = new HistoricoDAO();
        
        h.setCodigoProduto(valor1);
        h.setQuantidade(Integer.parseInt(txtQuantiS.getText()));
        h.setOperacao("Saída");
        dao.create(h);
        
        JOptionPane.showMessageDialog(null,"Baixa realizada com sucesso!");
        txtQuantiS.setText("");
        ComboBoxDS.setSelectedItem(null);
        }
        else{
            JOptionPane.showMessageDialog(null,"Erro valor superior aos itens no estoque!");
            txtQuantiS.setText("");
            ComboBoxDS.setSelectedItem(null);
        }
       
        
    }//GEN-LAST:event_ButtonSaidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(labelSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(labelSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(labelSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(labelSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new labelSaida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSaida;
    private javax.swing.JComboBox<Object> ComboBoxDS;
    private javax.swing.JButton buttonVoltarSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDataS;
    private javax.swing.JTextField txtQuantiS;
    // End of variables declaration//GEN-END:variables
}
