/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import javax.swing.JOptionPane;
import model.bean.Cor;
import model.bean.CorDAO;
import model.bean.Marca;
import model.bean.MarcaDAO;
import model.bean.Produto;
import model.bean.ProdutoDAO;

/**
 *
 * @author Aluno
 */
public class labelCadastro extends javax.swing.JFrame {

    /**
     * Creates new form labelCadastro
     */
    public labelCadastro() {
        initComponents();
        
        
        CorDAO dao = new CorDAO();
        
        for(Cor c: dao.read()){
            ComboBoxCor.addItem(c);
        }
        
        
        MarcaDAO mdao = new MarcaDAO();
        
        for(Marca m: mdao.read()){
            ComboBoxMarca.addItem(m);
        }
        
    }

       int valor1,valor2; 
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        buttonVoltarCP = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        ButtonInserir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        ComboBoxMarca = new javax.swing.JComboBox<>();
        ComboBoxCor = new javax.swing.JComboBox<>();

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonVoltarCP.setText("Voltar");
        buttonVoltarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarCPActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Descrição");

        jLabel3.setText("Marca");

        jLabel4.setText("Cor");

        ButtonInserir.setText("Inserir");
        ButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInserirActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço");

        ComboBoxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marca" }));
        ComboBoxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMarcaActionPerformed(evt);
            }
        });

        ComboBoxCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cor" }));
        ComboBoxCor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxCorItemStateChanged(evt);
            }
        });
        ComboBoxCor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ComboBoxCorFocusGained(evt);
            }
        });
        ComboBoxCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 212, Short.MAX_VALUE)
                        .addComponent(buttonVoltarCP))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ComboBoxMarca, javax.swing.GroupLayout.Alignment.TRAILING, 0, 102, Short.MAX_VALUE)
                            .addComponent(ComboBoxCor, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(ButtonInserir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(buttonVoltarCP)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarCPActionPerformed
        // TODO add your handling code here:
        new labelprincipal().setVisible(true);
            dispose();
    }//GEN-LAST:event_buttonVoltarCPActionPerformed

    private void ComboBoxCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCorActionPerformed
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_ComboBoxCorActionPerformed

    private void ComboBoxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMarcaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ComboBoxMarcaActionPerformed

    private void ButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInserirActionPerformed
        // TODO add your handling code here:
        MarcaDAO mdao = new MarcaDAO();
        CorDAO cdao = new CorDAO();
        
        Cor cor = (Cor) ComboBoxCor.getSelectedItem();
         valor1 = cor.getIdCor();
      
        Marca marca = (Marca) ComboBoxMarca.getSelectedItem();
        valor2 = marca.getIdMarca();
        
        Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        
        p.setCodigoProduto(Integer.parseInt(txtCodigo.getText()));
        p.setDescricaoProduto(txtDescricao.getText());
        p.setPrecoUnitProduto(Double.parseDouble(txtPreco.getText()));
        p.setIdCor(valor1);
        p.setIdMarca(valor2);
        dao.create(p);
        
        JOptionPane.showMessageDialog(null,"Produto cadastrado com sucesso!");
        txtCodigo.setText("");
        txtDescricao.setText("");
        txtPreco.setText("");
        ComboBoxCor.setSelectedItem("Cor");
        ComboBoxMarca.setSelectedItem("Marca");
    }//GEN-LAST:event_ButtonInserirActionPerformed

    private void ComboBoxCorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxCorItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ComboBoxCorItemStateChanged

    private void ComboBoxCorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboBoxCorFocusGained
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ComboBoxCorFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(labelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(labelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(labelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(labelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new labelCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonInserir;
    private javax.swing.JComboBox<Object> ComboBoxCor;
    private javax.swing.JComboBox<Object> ComboBoxMarca;
    private javax.swing.JButton buttonVoltarCP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
